
scope = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string></string>
	</array>
	<key>name</key>
	<string>%s</string>
	<key>patterns</key>
	<array>
%s
	</array>
	<key>scopeName</key>
	<string>%s.%s</string>
	<key>uuid</key>
	<string>%s</string>
</dict>
</plist>
"""

new_file = """{
	"include": ["lightmarkdown"],
	"autocompletion": false,
	"patterns": {
		$0"\\b(?hello)\\b": "dodgerblue",
		"world": "#ff0000"
	}
}"""

default_colours = """
		<dict>
			<key>settings</key>
			<dict>
				<key>background</key>
				<string>#000000</string>
				<key>caret</key>
				<string>#9F9F9F</string>
				<key>foreground</key>
				<string>#DEDEDE</string>
				<key>invisibles</key>
				<string>#343434</string>
				<key>lineHighlight</key>
				<string>#2A2A2A</string>
				<key>selection</key>
				<string>#424242</string>
			</dict>
		</dict>
"""

theme = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>%s</string>
	<key>author</key>
	<string>Generated by Synesthesia</string>
	<key>settings</key>
	<array>
		%s
		%s
	</array>
	<key>uuid</key>
	<string>%s</string>
</dict>
</plist>
"""

# <dict>
# 	<key>name</key>
# 	<string>Comment</string>
# 	<key>scope</key>
# 	<string>comment.block</string>
# 	<key>settings</key>
# 	<dict>
# 		<key>background</key>
# 		<string>#200020</string>
# 		<key>fontStyle</key>
# 		<string>italic</string>
# 		<key>foreground</key>
# 		<string>#404080</string>
# 	</dict>
# </dict>

pattern = """
		<dict>
			<key>match</key>
			<string>%s</string>
			<key>name</key>
			<string>%s</string>
		</dict>
"""

theme_element = """
		<dict>
			<key>name</key>
			<string>%s</string>
			<key>scope</key>
			<string>%s</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>%s</string>
			</dict>
		</dict>
"""

default_settings = """
{
	"color_scheme": "Packages/Synesthesia/%s.tmTheme"
}
"""
